### ISSUE TITLE
Invalid argument(s): Invalid return from platform getLocalTimezone()

### ISSUE THREAD

**Issue by wckum** [tjarvstrand/flutter_timezone#18] opened 2023-10-17 07:01 UTC
![image](https://github.com/tjarvstrand/flutter_timezone/assets/126537277/8073121f-1869-4c31-b918-087df56c9ba0)
Relevant code
```
final timezone = await FlutterTimezone.getLocalTimezone();
```

Getting this error in web on Chrome (Version 117.0.5938.132 (Official Build) (arm64)) using MacOS 14.0..
Any idea? Thanks for your effort!

**Comment by tjarvstrand** [comment] 2023-10-17 07:22
Hey there, thanks for the report.

Without knowing what was actually returned by the plugin, it pretty hard to offer any insight. Maybe you could put a breakpoint inside `flutter_timezone_web` and see what the call to `Intl.DateTimeFormat` actually results in?

**Comment by vixez** [comment] 2023-10-17 07:25
Hello @tjarvstrand ,
I have this issue as well.
This only happens on MacOS 14 Ventura.

I tried on several Mac's and all the Ventura ones are broken using any browser.
For example, my timezone used to be `Europe/Brussels` on 13.5, but now since 14.0 it says it's `CET`.

**Comment by wckum** [comment] 2023-10-17 07:35
Meanwhile I'm getting `undefined` for the value.. (not sure if this is what you're looking for)

![image](https://github.com/tjarvstrand/flutter_timezone/assets/126537277/5c0197f7-f16d-4206-bd6f-6b4ea44cb3a5)

**Comment by tjarvstrand** [comment] 2023-10-17 08:15
> Meanwhile I'm getting undefined for the value.. 

It seems like this is a browser/system problem. We rely on [`Intl.DateTimeFormat.resolvedOptions()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/resolvedOptions) to provide the timezone. 

>`timeZone`
>   The value provided for this property in the options argument; defaults to the runtime's default time zone. Should never be undefined.

If this is not correct, I'm not sure what to do about it?

Could you try calling `Intl.DateTimeFormat().resolvedOptions().timeZone;` in the browser console?

> For example, my timezone used to be Europe/Brussels on 13.5, but now since 14.0 it says it's CET

Though I understand how it can be problematic that this has changed, `CET` is a valid time zone. Even if you don't use it, you'll still have to take into account the fact that a lot of systems use abbreviated time zones rather than full names.

**Comment by tjarvstrand** [comment] 2023-10-17 08:20
BTW, @vixez 

> This only happens on MacOS 14 Ventura.

This version does not exist :) Do you mean MacOS 13 Ventura or MacOS 14 Sonoma?

**Comment by vixez** [comment] 2023-10-17 08:34
@tjarvstrand 

Oops you are right, I meant Sonoma 😄 

![Screenshot 2023-10-17 at 10 29 45](https://github.com/tjarvstrand/flutter_timezone/assets/3032294/243951d5-3183-40b7-afad-222b25a58196)

I agree that this is a tough one to fix, I don't really know where to start looking to get it back to `Europe/Brussels`.
In my app I do more calculations with timezones, and for this I use the `flutter_timezone` package in combination with the [timezone](https://pub.dev/packages/timezone) package.
The issue is that the `timezone` package does not accept `CET` as a valid timezone.

Since pretty much every user using my app is in the `Europe/Brussels` timezone, for now I catch it like this

```
  static Future updateLocalTimeZone() async {
    localTimeZone = await getLocalTimeZone();
    if (localTimeZone == 'CET' || localTimeZone == 'undefined') {
      //TODO: This is a MacOS 14 Sonoma issue
      //Ticket: https://github.com/tjarvstrand/flutter_timezone/issues/18
      localTimeZone = 'Europe/Brussels';
    }
  }
```

But of course this is far from ideal, or futureproof.

**Comment by wckum** [comment] 2023-10-17 09:48
Seems like it's a system/browser issue then like you said... On chrome (even after latest update on Version 118.0.5993.70 (Official Build) (arm64)) it is still returning `undefined` .. On firefox it at least returns something .. I guess you can close this issue if you want...?

**Comment by tjarvstrand** [comment] 2023-10-17 12:09
> But of course this is far from ideal, or futureproof.

Yeah, dealing with time is a PITA. If you're in a position to do so, I'd recommend you to do all your storage and calculations in UTC and only deal with time zones as close to the user as possible.

> I guess you can close this issue if you want...?

Thanks. Given how thin this library is, I don't think there's much that can, or should be done about it here so I'll close this for now. Sorry I couldn't be of more help.

**Closed by tjarvstrand** 2023-10-17 12:09 UTC
